[project]
name = "rl_for_llms"
version = "1.0.0"
description = "rl_for_llms"
readme = "README.md"
requires-python = "==3.13.11"
dependencies = [
    "datasets==4.4.1",
    "peft==0.18.0",
    "pydantic==2.12.5",
    "torch==2.9.1",
    "transformers[hf-xet]==4.57.3",
    "wandb==0.23.1",
    "math-verify==0.8.0",
    "trl==0.26.1",
]

[dependency-groups]
dev = [
    "mypy==1.19.0",
    "ruff==0.14.9",
    "pytest==9.0.2",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D100", "D104", "D203", "D213", "COM812", "RET504", "PLR0913", "E501"]

[tool.mypy]
strict = true
ignore_missing_imports = true
exclude_gitignore = true
